#!/usr/bin/env bash
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/config"
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_BASE_PATH/common/functions"
source "$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/functions"

postgres-wal-disable-cmd() {
  [[ -z $2 ]] && dokku_log_fail "Please specify a name for the service"
  verify_service_name "$2"

  local SERVICE="$2"
  local SERVICE_ROOT="$PLUGIN_DATA_ROOT/$SERVICE"
  local SERVICE_NAME=$(get_service_name "$SERVICE")
  local PASSWORD=$(cat "$SERVICE_ROOT/PASSWORD")
  local DISABLE_SCRIPT_PATH="$(dirname "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)")/scripts/disable_wal.sh"

  test -e "$SERVICE_ROOT/backups/base" || dokku_log_fail "WAL seems to be already disabled"

  dokku_log_verbose_quiet "Writing postgresql.conf and pg_hba.conf"
  docker run --rm -i -v "$SERVICE_ROOT/data:/var/lib/postgresql/data" "$PLUGIN_IMAGE:$PLUGIN_IMAGE_VERSION" bash -s < $DISABLE_SCRIPT_PATH

  service_stop "$SERVICE"
  service_start "$SERVICE"

  dokku_log_verbose_quiet "WAL incremental backup disabled"
  dokku_log_verbose_quiet "The base backup and the WAL segments in $SERVICE_ROOT/backups are NOT removed"
}

postgres-wal-disable-cmd "$@"
